### ISSUE TITLE
About react-guitar

### ISSUE THREAD

**Issue by 4lejandrito** [cgm42/WorkLand#59]
Hi! I'm Alex, author of react-guitar.

[I've seen](https://github.com/4lejandrito/react-guitar/network/dependents?package_id=UGFja2FnZS00NTY4NDc2Mzg%3D) you're using react-guitar on this project. I had a quick look at your README and it looks awesome, however I could not log in to your plarform :(

I was wondering what you're using react-guitar for. Do you have some screenshots? I'd like to add a link to this project to my README so that I can showcase real use cases.

Thanks!!

**Comment by cgm42** [comment]
Hi Alex, 
Thanks for visiting.  I added a video to README.  I was going to add a GIF showing the guitar, but without audio, it didn't make much sense. 

As for the login issue, free Heroku server seem to act up every now and then and just need to be restarted to make login work again. Also, the browser has to support 3rd party cookies.  There might be other issue causing it, but I'm having a hard time pinning it down. What OS/browser are you using?

**Comment by 4lejandrito** [comment]
Hi! 

Sorry for the late response! 

I tried again now and it worked. It's so cool!

I already linked to Workland from my README. See https://github.com/4lejandrito/react-guitar/commit/3acee7a21af26d3314659606fa423022ea1b15f2.

Thanks!
